all:
  hosts:
    app1:
      ansible_host: localhost
      # ansible_user: pi
      ansible_connection: local
    db1:
      ansible_host: localhost
      # ansible_user: pi
      ansible_connection: local
  children:
    env:
      hosts:
        app1:
    env.secret:
      hosts:
        app1:
    app:
      hosts:
        app1:
